FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app/server

COPY server/package*.json ./
RUN npm ci --omit=dev

COPY server ./
COPY --from=frontend-builder /app/dist /app/dist

EXPOSE 51130
CMD ["npm", "run", "start"]
